"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Home from "./page";
import { ThemeProviderWrapper } from "../contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Twenty Test",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProviderWrapper>
      <html lang="en">
        {/* <body className={inter.className}>{children}</body> */}
        <body className={inter.className}>
          <Home>{children}</Home>
        </body>
      </html>
    </ThemeProviderWrapper>
  );
}
